---
abstract: 'IOTA Marathon website'
author:
  - 'Roger Pettett <rmp@psyphi.net>'
build_requires:
  Test::More: 0.62
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ham-DXCC
provides:
  Ham::DXCC:
    file: lib/Ham/DXCC.pm
    version: 0.1
requires:
  Carp: 1.04
  English: 1.02
  XML::XPath: 1.13
  base: 2.07
  strict: 1.03
  warnings: 1.05
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.1
